In [1]:
from sklearn.datasets import make_regression
import numpy as np
import time

In [2]:
X,y = make_regression(n_samples = 100, n_features = 4 , n_informative = 3 , n_targets =1 ,noise = 40)

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
lr = LinearRegression()

In [5]:
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

In [6]:
from sklearn.metrics import accuracy_score, r2_score

In [7]:
r2_score(y_test,y_pred)

0.9365819531795697

In [8]:
lr.coef_

array([49.87673679, 98.93183796, 86.64530032,  2.67644982])

In [9]:
X

array([[-2.24582347e+00, -1.17926906e+00,  8.78698883e-02,
        -6.37175143e-01],
       [-1.00986035e+00, -9.03732085e-01, -1.01910275e-01,
         4.57676368e-01],
       [-1.01363918e+00, -1.58680734e+00,  1.25536869e+00,
         2.31464542e-01],
       [-4.98152854e-01,  9.32594666e-01, -1.05494197e-01,
         4.58795956e-01],
       [ 8.50507567e-01,  1.14387630e+00, -4.66635477e-01,
         7.73622884e-01],
       [-1.77409286e+00,  1.50268912e+00, -2.73227754e+00,
        -9.20188367e-01],
       [ 4.90704851e-01,  3.57437078e-01,  4.62380821e-01,
         1.46448110e+00],
       [ 2.95616103e-01, -4.75123626e-01,  1.25607266e+00,
         2.00037937e-01],
       [ 1.60563441e+00,  2.62601819e-02,  2.44917279e+00,
         9.23962908e-01],
       [-1.01011129e+00,  2.99312885e-01,  1.98116497e-01,
        -1.27276413e+00],
       [-6.85893778e-01, -1.19330462e+00, -1.87331776e+00,
         2.48150719e-01],
       [-1.31648383e+00,  1.67700227e-01,  2.03182552e+00,
      

In [17]:
class BGD:
    def __init__(self,learning_rate,epoch):
        self.intercept_ = None
        self.coef_ = None
        self.lr = learning_rate
        self.epoch = epoch
        
    def fit(self,X_train,y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])  # here i had make the array of coefficent of size equal to the no of columns 
        for i in range(self.epoch):
            y_hat = np.dot(X_train,self.coef_)+ self.intercept_   # predicted y value and it is the row of all the predicted value
            intercep_der = -2*np.mean(y_train - y_hat)  # this is the intercept derivative
            self.intercept_ = self.intercept_ - (self.lr * intercep_der)   # gradient desent on the intercept
            coef_der = -2*np.dot((y_train - y_hat),X_train)/X_train.shape[0]  # derivatie of the loss function with respect to the coefficent of the y_hat and divide by X_train.shape[0] which is equal to the no of samples
            self.coef_ = self.coef_ - (self.lr*coef_der)  # updated value of coefficeint of the y_hat
        print(self.coef_,self.intercept_)
    def predict(self,X_test):
        return np.dot(X_test,self.coef_)+self.intercept_

In [13]:
gd = BGD(0.05,100)

In [14]:
start = time.time()
gd.fit(X_train,y_train)
print('Time taken is:', time.time()-start)

[49.88122474 98.92690514 86.64347726  2.67229348] -6.818592377262111
Time taken is: 0.04548192024230957


In [15]:
y_predict= gd.predict(X_test)

In [16]:
r2_score(y_test,y_predict)

0.9365861877748115