In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df=df.drop(columns = ['PassengerId','Name', 'Ticket','Cabin', 'SibSp'])

In [6]:
df.head()

Survived  Pclass     Sex   Age  Parch     Fare Embarked
0         0       3    male  22.0      0   7.2500        S
1         1       1  female  38.0      0  71.2833        C
2         1       3  female  26.0      0   7.9250        S
3         1       1  female  35.0      0  53.1000        S
4         0       3    male  35.0      0   8.0500        S

In [15]:
df.isnull().sum() 

Survived      0
Pclass        0
Sex           0
Age         177
Parch         0
Fare          0
Embarked      2
dtype: int64

In [16]:
df.nunique()

Survived      2
Pclass        3
Sex           2
Age          88
Parch         7
Fare        248
Embarked      3
dtype: int64

In [17]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns = ['Survived']), df['Survived'], test_size = 0.2, random_state = 4)

In [33]:
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy = 'most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.fit_transform(X_test[['Age']])
X_test_embarked = si_embarked.fit_transform(X_test[['Embarked']])


In [31]:
X_train_age

array([[30.02047368],
       [60.        ],
       [36.        ],
       [30.02047368],
       [30.02047368],
       [36.        ],
       [ 3.        ],
       [70.        ],
       [30.        ],
       [21.        ],
       [35.        ],
       [21.        ],
       [20.        ],
       [27.        ],
       [19.        ],
       [38.        ],
       [19.        ],
       [39.        ],
       [30.02047368],
       [33.        ],
       [39.        ],
       [30.02047368],
       [33.        ],
       [22.        ],
       [18.        ],
       [30.02047368],
       [20.        ],
       [29.        ],
       [ 0.83      ],
       [34.5       ],
       [45.        ],
       [18.        ],
       [18.        ],
       [25.        ],
       [46.        ],
       [24.        ],
       [39.        ],
       [19.        ],
       [30.02047368],
       [36.        ],
       [30.02047368],
       [29.        ],
       [15.        ],
       [ 9.        ],
       [52.        ],
       [20

In [40]:
ohe_sex = OneHotEncoder(sparse_output = False,dtype = np.int32, handle_unknown = 'ignore')
ohe_embarked = OneHotEncoder(sparse_output = False,handle_unknown = 'ignore')

X_train_sex= ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex= ohe_sex.fit_transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.fit_transform(X_test_embarked)


In [41]:
X_train_sex

array([[0, 1],
       [0, 1],
       [0, 1],
       ...,
       [0, 1],
       [0, 1],
       [0, 1]])

In [43]:
X_train

Pclass     Sex   Age  Parch     Fare Embarked
42        3    male   NaN      0   7.8958        C
684       2    male  60.0      1  39.0000        S
605       3    male  36.0      0  15.5500        S
409       3  female   NaN      1  25.4667        S
740       1    male   NaN      0  30.0000        S
..      ...     ...   ...    ...      ...      ...
360       3    male  40.0      4  27.9000        S
709       3    male   NaN      1  15.2458        C
439       2    male  31.0      0  10.5000        S
174       1    male  56.0      0  30.6958        C
122       2    male  32.5      0  30.0708        C

[712 rows x 6 columns]

In [46]:
X_train_rem = X_train.drop(columns = ['Sex','Age','Embarked'])
X_test_rem = X_test.drop(columns = ['Sex','Age','Embarked'])

In [54]:
X_train_transform = np.concatenate((X_train_rem,X_train_sex,X_train_age,X_train_embarked), axis =1)
X_test_transform = np.concatenate((X_test_rem,X_test_sex,X_test_age,X_test_embarked), axis =1)

In [51]:
X_train_transform

array([[ 3.    ,  0.    ,  7.8958, ...,  1.    ,  0.    ,  0.    ],
       [ 2.    ,  1.    , 39.    , ...,  0.    ,  0.    ,  1.    ],
       [ 3.    ,  0.    , 15.55  , ...,  0.    ,  0.    ,  1.    ],
       ...,
       [ 2.    ,  0.    , 10.5   , ...,  0.    ,  0.    ,  1.    ],
       [ 1.    ,  0.    , 30.6958, ...,  1.    ,  0.    ,  0.    ],
       [ 2.    ,  0.    , 30.0708, ...,  1.    ,  0.    ,  0.    ]])

In [52]:
clf =DecisionTreeClassifier()

In [53]:
clf.fit(X_train_transform,y_train)

DecisionTreeClassifier()

In [57]:
y_pred = clf.predict(X_test_transform)

In [59]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8212290502793296

In [60]:
import pickle

In [61]:
pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))

FileNotFoundError: [Errno 2] No such file or directory: 'models/ohe_sex.pkl'